[project]
name = "fiona"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Miguel Bernal Marin", email = "migubern@qti.qualcomm.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
fiona = "fiona:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
